### PR TITLE
Add gitignore

### PR DESCRIPTION
**Pull request by Xwilarg**
Hey,

I added a gitignore so you won't push useless files (object files, executable, Sublime Text configuration files...)

Stay safe :).

### CODE REVIEW

**Comment by acorrenson** [comment]
Thank you !! :)

**Comment by Xwilarg** [comment]
You should consider adding others files like "test" and ".DS_Store" in it :)

**Comment by acorrenson** [comment]
Test is not a useless file ^^. It is a part of the development process. This script is made to automate testing. Ds_store is a file produced buy MacOSX. I should add this file to the gitignore

**Comment by Xwilarg** [comment]
Oh, you might want to call it "test.sh" then

**Pull request merged**
